// start of GopherCAN_names.c
//  (auto-generated)
//  This header file houses the names from the configuration file in arrays
//  that can be referenced by ID

#include "GopherCAN_names.h"

// human-readable names
char* name_strings[NUM_OF_PARAMETERS] =
{
    "CAN Command",
    "Engine RPM (ECU)",
    "Wheel Slip (ECU)",
    "Wheel Slip (ECU)",
    "Engine RPM Target (ECU)",
    "Wheel Speed Front Left (ECU)",
    "Wheel Speed Front Right (ECU)",
    "Wheel Speed Rear Left (ECU)",
    "Wheel Speed Rear Left (ECU)",
    "Ignition Cut Level (ECU)",
    "Battery Voltage (ECU)",
    "Engine Temp (ECU)",
    "Inlet Air Temp (ECU)",
    "Lambda 1 Ratio (ECU)",
    "Throttle Position 1 (ECU)",
    "Throttle Position 2 (ECU)",
    "Pedal Position 1 (ECU)",
    "Pedal Position 2 (ECU)",
    "Manifold Air Pressure (ECU)",
    "Fuel Cut Level (ECU)",
    "Ignition Advance (ECU)",
    "Oil Pressure (ECU)",
    "Oil Temp (ECU)",
    "Fuel Pressure (ECU)",
    "Throttle Position Required (ECU)",
    "Brake Pressure Front (ECU)",
    "ETC Duty Cycle (ECU)",
    "Fan Duty Cycle (ECU)",
    "Fan Oil Duty Cycle (ECU)",
    "Water Pump Duty Cycle (ECU)",
    "Brake Light Duty Cycle (ECU)",
    "Warning Light Duty Cycle (ECU)",
    "5V Aux Voltage (ECU)",
    "5V Eng Voltage (ECU)",
    "GPS Latitude (ECU)",
    "GPS Longitude (ECU)",
    "brake_pressure_rear",
    "steering_angle",
    "throttle_position",
    "acceleration",
    "Ride Height Rear",
    "Ride Height Front",
    "Rear Right Shock Position",
    "Rear Left Shock Position",
    "Front Left Shock Position",
    "Front Right Shock Position",
    "Right Radiator Pressure In",
    "Right Radiator Pressure Out",
    "Right Radiator Pressure Drop",
    "Right Radiator in Temperature",
    "Right Radiator out Temperature",
    "Left Radiator Pressure In",
    "Left Radiator Pressure Out",
    "Left Radiator Pressure Drop",
    "Left Radiator in Temperature",
    "Left Radiator out Temperature",
    "Air Tank Pressure",
    "Pnumatic Line Pressure",
    "Water Pump Pressure In",
    "Water Pump Pressure Out",
    "Main Circuit Flow Rate",
    "Exhaust Temp 1",
    "Exhaust Temp 2",
    "Exhaust Temp 3",
    "Exhaust Temp 4",
    "Exhaust Temp 5",
    "Lambda Header 1",
    "Lambda Header 2",
    "Oil Cooler Temp In",
    "Oil Cooler Temp Out",
    "Oil Cooler Pressure In",
    "Oil Cooler Pressure Out",
    "Fire Wall Temp",
    "Yaw Rate",
    "Y-axis acceleration",
    "Roll Rate",
    "X-axis acceleration",
    "Z-axis acceleration",
    "Tire Temp Rear Right Channel 1",
    "Tire Temp Rear Right Channel 2",
    "Tire Temp Rear Right Channel 3",
    "Tire Temp Rear Right Channel 4",
    "Tire Temp Rear Right Channel 5",
    "Tire Temp Rear Right Channel 6",
    "Tire Temp Rear Right Channel 7",
    "Tire Temp Rear Right Channel 8",
    "Tire Temp Rear Right Channel 9",
    "Tire Temp Rear Right Channel 10",
    "Tire Temp Rear Right Channel 11",
    "Tire Temp Rear Right Channel 12",
    "Tire Temp Rear Right Channel 13",
    "Tire Temp Rear Right Channel 14",
    "Tire Temp Rear Right Channel 15",
    "Tire Temp Rear Right Channel 16",
    "Tire Temp Rear Left Channel 1",
    "Tire Temp Rear Left Channel 2",
    "Tire Temp Rear Left Channel 3",
    "Tire Temp Rear Left Channel 4",
    "Tire Temp Rear Left Channel 5",
    "Tire Temp Rear Left Channel 6",
    "Tire Temp Rear Left Channel 7",
    "Tire Temp Rear Left Channel 8",
    "Tire Temp Rear Left Channel 9",
    "Tire Temp Rear Left Channel 10",
    "Tire Temp Rear Left Channel 11",
    "Tire Temp Rear Left Channel 12",
    "Tire Temp Rear Left Channel 13",
    "Tire Temp Rear Left Channel 14",
    "Tire Temp Rear Left Channel 15",
    "Tire Temp Rear Left Channel 16",
    "Tire Temp Front Left Channel 1",
    "Tire Temp Front Left Channel 2",
    "Tire Temp Front Left Channel 3",
    "Tire Temp Front Left Channel 4",
    "Tire Temp Front Left Channel 5",
    "Tire Temp Front Left Channel 6",
    "Tire Temp Front Left Channel 7",
    "Tire Temp Front Left Channel 8",
    "Tire Temp Front Left Channel 9",
    "Tire Temp Front Left Channel 10",
    "Tire Temp Front Left Channel 11",
    "Tire Temp Front Left Channel 12",
    "Tire Temp Front Left Channel 13",
    "Tire Temp Front Left Channel 14",
    "Tire Temp Front Left Channel 15",
    "Tire Temp Front Left Channel 16",
    "Tire Temp Front Right Channel 1",
    "Tire Temp Front Right Channel 2",
    "Tire Temp Front Right Channel 3",
    "Tire Temp Front Right Channel 4",
    "Tire Temp Front Right Channel 5",
    "Tire Temp Front Right Channel 6",
    "Tire Temp Front Right Channel 7",
    "Tire Temp Front Right Channel 8",
    "Tire Temp Front Right Channel 9",
    "Tire Temp Front Right Channel 10",
    "Tire Temp Front Right Channel 11",
    "Tire Temp Front Right Channel 12",
    "Tire Temp Front Right Channel 13",
    "Tire Temp Front Right Channel 14",
    "Tire Temp Front Right Channel 15",
    "Tire Temp Front Right Channel 16",
    "Upshift button from steering wheel",
    "Downshift button from steering wheel",
    "Clutch button from steering wheel",
    "DRS button from steering wheel",
    "Aux2 button from steering wheel",
    "Aux3 button from steering wheel",
    "Neutral signal",
    "Shifter Position",
    "Clutch Position",
    "Target RPM during a shift",
    "Transmission speed, measured at the clutch",
    "Current Gear",
    "Target Gear During a shift",
    "True if we are Currently moving",
    "True if we are Currently blipping the ECU",
    "True if we are using the clutch during a shift",
    "True if a shift is successful",
    "Anti stall active",
    "Front Right Wing Angle",
    "Front Left Wing Angle",
    "Rear Wing Angle",
    "Current from PDM channel 1",
    "Current from PDM channel 2",
    "Current from PDM channel 3",
    "Current from PDM channel 4",
    "Current from PDM channel 5",
    "Current from PDM channel 6",
    "Current from PDM channel 7",
    "Current from PDM channel 8",
    "Current from PDM channel 9",
    "Current from PDM channel 10",
    "Current from PDM channel 11",
    "Current from PDM channel 12",
    "Current from PDM channel 13",
    "Current from PDM channel 14",
    "Current from PDM channel 15",
    "Current from PDM channel 16",
    "Current from PDM channel 17",
    "Current from PDM channel 18",
    "Current from PDM channel 19",
    "Current from PDM channel 20",
    "Switch Voltage",
    "Switch Temperature"
    
};

// parameter units
char* unit_strings[NUM_OF_PARAMETERS] =
{
    "cmd",
    "rpm",
    "kph",
    "kph",
    "rpm",
    "rpm",
    "kph",
    "kph",
    "kph",
    "kPa",
    "C",
    "C",
    "C",
    "LA",
    "percent",
    "percent",
    "percent",
    "percent",
    "kPa",
    "percent",
    "dbtdc",
    "kPa",
    "C",
    "kPa",
    "percent",
    "psi",
    "percent",
    "percent",
    "percent",
    "percent",
    "percent",
    "percent",
    "percent",
    "percent",
    "deg",
    "deg",
    "PSI",
    "degrees",
    "number",
    "m/s^2",
    "mm",
    "mm",
    "mm",
    "mm",
    "mm",
    "mm",
    "PSI",
    "PSI",
    "PSI",
    "C",
    "C",
    "PSI",
    "PSI",
    "PSI",
    "C",
    "C",
    "PSI",
    "PSI",
    "PSI",
    "PSI",
    "Liters/Minute",
    "C",
    "C",
    "C",
    "C",
    "C",
    "lam",
    "lam",
    "C",
    "C",
    "C",
    "C",
    "C",
    "degrees per second",
    "Gs",
    "degrees per second",
    "Gs",
    "Gs",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "mm",
    "mm",
    "rpm",
    "rpm",
    "gear",
    "gear",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "duty",
    "duty",
    "duty",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "Volts",
    "C"
    
};

// parameter types
PARAM_TYPE_t param_types[NUM_OF_PARAMETERS] = 
{
	CMD,
    UINT_16,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    FLOAT,
    FLOAT,
    UINT_32,
    UINT_32,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_32,
    UINT_32,
    UINT_32,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT
    
};


// End of GopherCAN_names.c

