// GopherCAN_names.h
//  (auto-generated)
//  This header file houses externs for the param names in GopherCAN


#ifndef GOPHERCAN_NAMES_H
#define GOPHERCAN_NAMES_H

// Generated by GopherCANnon

#ifndef NUM_OF_PARAMETERS
#define NUM_OF_PARAMETERS 2
#endif // NUM_OF_PARAMETERS

typedef enum
{
	CMD = 0,
	UINT_8 = 1,
	UINT_16 = 2,
	UINT_32 = 3,
	UINT_64 = 4,
	SINT_8 = 5,
	SINT_16 = 6,
	SINT_32 = 7,
	SINT_64 = 8,
	FLOAT = 9
} PARAM_TYPE_t;

extern char* name_strings[NUM_OF_PARAMETERS];
extern char* unit_strings[NUM_OF_PARAMETERS];
extern PARAM_TYPE_t param_types[NUM_OF_PARAMETERS];

#endif // GOPHERCAN_NAMES_H

// End of GopherCAN_names.h

