// start of GopherCAN_names.c
//  (auto-generated)
//  This header file houses the names from the configuration file in arrays
//  that can be referenced by ID

#include "GopherCAN_names.h"

// human-readable names
char* name_strings[NUM_OF_PARAMETERS] =
{
    "CAN Command",
    "Battery 0 Temp",
    "Battery 1 Temp",
    "Battery 2 Temp",
    "Battery 3 Temp",
    "Battery 4 Temp",
    "Battery 5 Temp",
    "Battery 6 Temp",
    "Battery 7 Temp",
    "Battery 8 Temp",
    "Battery 9 Temp",
    "Battery 10 Temp",
    "Battery 11 Temp",
    "Battery 12 Temp",
    "Battery 13 Temp",
    "Battery 14 Temp",
    "Battery 15 Temp",
    "Battery 16 Temp",
    "Battery 17 Temp",
    "Battery 18 Temp",
    "Battery 19 Temp",
    "Battery 20 Temp",
    "Battery 21 Temp",
    "Battery 22 Temp",
    "Battery 23 Temp",
    "Battery 24 Temp",
    "Battery 25 Temp",
    "Battery 26 Temp",
    "Battery 27 Temp",
    "Battery 28 Temp",
    "Battery 29 Temp",
    "Battery 30 Temp",
    "Battery 31 Temp",
    "Battery 32 Temp",
    "Battery 33 Temp",
    "Battery 34 Temp",
    "Battery 35 Temp",
    "Battery 36 Temp",
    "Battery 37 Temp",
    "Battery 38 Temp",
    "Battery 39 Temp",
    "Battery 40 Temp",
    "Battery 41 Temp",
    "Battery 42 Temp",
    "Battery 43 Temp",
    "Battery 44 Temp",
    "Battery 45 Temp",
    "Battery 46 Temp",
    "Battery 47 Temp",
    "Battery 48 Temp",
    "Battery 49 Temp",
    "Battery 50 Temp",
    "Battery 51 Temp",
    "Battery 52 Temp",
    "Battery 53 Temp",
    "Battery 54 Temp",
    "Battery 55 Temp",
    "Battery 56 Temp",
    "Battery 57 Temp",
    "Battery 58 Temp",
    "Battery 59 Temp",
    "Battery 60 Temp",
    "Battery 61 Temp",
    "Battery 62 Temp",
    "Battery 63 Temp",
    "Battery 64 Temp",
    "Battery 65 Temp",
    "Battery 66 Temp",
    "Battery 67 Temp",
    "Battery 68 Temp",
    "Battery 69 Temp",
    "Battery 70 Temp",
    "Battery 71 Temp",
    "Battery 72 Temp",
    "Battery 73 Temp",
    "Battery 74 Temp",
    "Battery 75 Temp",
    "Battery 76 Temp",
    "Battery 77 Temp",
    "Battery 78 Temp",
    "Battery 79 Temp",
    "Battery 80 Temp",
    "Battery 81 Temp",
    "Battery 82 Temp",
    "Battery 83 Temp",
    "Battery 84 Temp",
    "Battery 85 Temp",
    "Battery 86 Temp",
    "Battery 87 Temp",
    "Battery Minimum Temp",
    "Battery Average Temp",
    "Battery Maximum Temp",
    "Current from PDM channel 1",
    "Current from PDM channel 2",
    "Current from PDM channel 3",
    "Current from PDM channel 4",
    "Current from PDM channel 5",
    "Current from PDM channel 6",
    "Current from PDM channel 7",
    "Current from PDM channel 8",
    "Current from PDM channel 9",
    "Current from PDM channel 10",
    "Current from PDM channel 11",
    "Current from PDM channel 12",
    "Current from PDM channel 13",
    "Current from PDM channel 14",
    "Current from PDM channel 15",
    "Current from PDM channel 16",
    "Current from PDM channel 17",
    "Current from PDM channel 18",
    "Current from PDM channel 19",
    "Current from PDM channel 20",
    "Switch Voltage",
    "Switch Temperature",
    "Pedal 1 Position",
    "Pedal 2 Position",
    "Motor Current 1",
    "Motor Current 2",
    "Brake Pressure Front",
    "Wheel Speed Front Left",
    "Wheel Speed Front Right",
    "Shock Pos Front Left",
    "Shock Pos Front Right",
    "Shock Pos Rear Left",
    "Shock Pos Rear Right",
    "Steering Angle",
    "Battery Voltage",
    "Ready to drive button",
    "Ready to drive buzzer",
    "Water Pump Duty",
    "Water Pump Duty",
    "Brake Light Duty",
    "VCU Status"
    "Dummy CAN param for Temp Board"
    
};

// parameter units
char* unit_strings[NUM_OF_PARAMETERS] =
{
    "cmd",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "Volts",
    "C",
    "percent",
    "percent",
    "A",
    "A",
    "psi",
    "mph",
    "mph",
    "mm",
    "mm",
    "mm",
    "mm",
    "Degrees",
    "Voltage",
    "Bool",
    "percent",
    "percent",
    "percent",
    "percent",
    "bits",
    "C",

    
};

// parameter types
PARAM_TYPE_t param_types[NUM_OF_PARAMETERS] = 
{
	CMD,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    UINT_32,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    UINT_16,
    FLOAT,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    FLOAT
    
};


// End of GopherCAN_names.c

