// start of GopherCAN_names.c
//  (auto-generated)
//  This header file houses the names from the configuration file in arrays
//  that can be referenced by ID

#include "GopherCAN_names.h"

// human-readable names
char* name_strings[NUM_OF_PARAMETERS] =
{
    "CAN Command",
    "Engine RPM",
    "Wheel Slip (Percent)",
    "Wheel Slip Target (ECU)",
    "Engine RPM Target (ECU)",
    "Wheel Speed FL",
    "Wheel Speed FR",
    "Wheel Speed RL",
    "Wheel Speed RR",
    "Ign Cut Level Total",
    "Bat Volts ECU",
    "Engine Temp",
    "Air Temp Inlet",
    "Lambda 1",
    "Throttle Pos",
    "Throttle Pos 2",
    "Pedal Position 1",
    "Pedal Position 2",
    "Manifold Pres",
    "Fuel Cut Level Total",
    "Ignition Advance",
    "Eng Oil Pres",
    "Eng Oil Temp",
    "Fuel Pres",
    "Throttle Position Required",
    "Brake Pressure Front",
    "ETC Duty Cycle (ECU)",
    "Fan Duty Cycle (ECU)",
    "Fan Oil Duty Cycle (ECU)",
    "Water Pump Duty Cycle (ECU)",
    "Brake Light Duty Cycle (ECU)",
    "Warning Light Duty Cycle (ECU)",
    "5V Aux Supply",
    "5V Eng Voltage",
    "GPS Latitude",
    "GPS Longitude",
    "Brake Pressure Rear",
    "Steering Angle",
    "throttle_position",
    "acceleration",
    "Ride Height Rear",
    "Ride Height Front",
    "Shock Pot Rear Right",
    "Shock Pot Rear Left",
    "Shock Pot Front Left",
    "Shock Pot Front Right",
    "Right Radiator Pressure In",
    "Right Radiator Pressure Out",
    "Right Radiator Pressure Drop",
    "Right Radiator in Temperature",
    "Right Radiator out Temperature",
    "Left Radiator Pressure In",
    "Left Radiator Pressure Out",
    "Left Radiator Pressure Drop",
    "Left Radiator in Temperature",
    "Left Radiator out Temperature",
    "Air Tank Pressure",
    "Pnumatic Line Pressure",
    "Water Pump Inlet Pressure",
    "Water Pump Outlet Pressure",
    "Main Circuit Flow Rate",
    "Exhaust Temp",
    "Exhaust Temp 2",
    "Exhaust Temp 3",
    "Exhaust Temp 4",
    "Exhaust Temp 5",
    "Lambda Header 1",
    "Lambda Header 2",
    "Oil Cooler Temp In",
    "Oil Cooler Temp Out",
    "Oil Cooler Pressure In",
    "Oil Cooler Pressure Out",
    "Fire Wall Temp",
    "Yaw Rate",
    "Lateral Acceleration",
    "Roll Rate",
    "Longitudinal Acceleration",
    "Vertical Acceleration",
    "Brake Temp Front Left",
    "Brake Temp Front Right",
    "Brake Temp Rear Left",
    "Brake Temp Rear Right",
    "Tire Temp Rear Right Channel 1",
    "Tire Temp Rear Right Channel 2",
    "Tire Temp Rear Right Channel 3",
    "Tire Temp Rear Right Channel 4",
    "Tire Temp Rear Right Channel 5",
    "Tire Temp Rear Right Channel 6",
    "Tire Temp Rear Right Channel 7",
    "Tire Temp Rear Right Channel 8",
    "Tire Temp Rear Right Channel 9",
    "Tire Temp Rear Right Channel 10",
    "Tire Temp Rear Right Channel 11",
    "Tire Temp Rear Right Channel 12",
    "Tire Temp Rear Right Channel 13",
    "Tire Temp Rear Right Channel 14",
    "Tire Temp Rear Right Channel 15",
    "Tire Temp Rear Right Channel 16",
    "Tire Temp Rear Left Channel 1",
    "Tire Temp Rear Left Channel 2",
    "Tire Temp Rear Left Channel 3",
    "Tire Temp Rear Left Channel 4",
    "Tire Temp Rear Left Channel 5",
    "Tire Temp Rear Left Channel 6",
    "Tire Temp Rear Left Channel 7",
    "Tire Temp Rear Left Channel 8",
    "Tire Temp Rear Left Channel 9",
    "Tire Temp Rear Left Channel 10",
    "Tire Temp Rear Left Channel 11",
    "Tire Temp Rear Left Channel 12",
    "Tire Temp Rear Left Channel 13",
    "Tire Temp Rear Left Channel 14",
    "Tire Temp Rear Left Channel 15",
    "Tire Temp Rear Left Channel 16",
    "Tire Temp Front Left Channel 1",
    "Tire Temp Front Left Channel 2",
    "Tire Temp Front Left Channel 3",
    "Tire Temp Front Left Channel 4",
    "Tire Temp Front Left Channel 5",
    "Tire Temp Front Left Channel 6",
    "Tire Temp Front Left Channel 7",
    "Tire Temp Front Left Channel 8",
    "Tire Temp Front Left Channel 9",
    "Tire Temp Front Left Channel 10",
    "Tire Temp Front Left Channel 11",
    "Tire Temp Front Left Channel 12",
    "Tire Temp Front Left Channel 13",
    "Tire Temp Front Left Channel 14",
    "Tire Temp Front Left Channel 15",
    "Tire Temp Front Left Channel 16",
    "Tire Temp Front Right Channel 1",
    "Tire Temp Front Right Channel 2",
    "Tire Temp Front Right Channel 3",
    "Tire Temp Front Right Channel 4",
    "Tire Temp Front Right Channel 5",
    "Tire Temp Front Right Channel 6",
    "Tire Temp Front Right Channel 7",
    "Tire Temp Front Right Channel 8",
    "Tire Temp Front Right Channel 9",
    "Tire Temp Front Right Channel 10",
    "Tire Temp Front Right Channel 11",
    "Tire Temp Front Right Channel 12",
    "Tire Temp Front Right Channel 13",
    "Tire Temp Front Right Channel 14",
    "Tire Temp Front Right Channel 15",
    "Tire Temp Front Right Channel 16",
    "Upshift_Raw_Input",
    "Downshift_Raw_Input",
    "Clutch_Raw_Input",
    "Clutch button (slow)",
    "Front aero button",
    "Rear aero button",
    "Neutral signal",
    "Shifter Position",
    "Clutch Position",
    "Target RPM during a shift",
    "Transmission speed",
    "Current Gear",
    "Target Gear During a shift",
    "Currently moving",
    "Blip Active",
    "Clutch Shifting",
    "Shift Success",
    "Anti stall active",
    "Front Right Wing Angle",
    "Front Left Wing Angle",
    "Rear Wing Angle",
    "Current from PDM channel 0",
    "Current from PDM channel 1",
    "Current from PDM channel 2",
    "Current from PDM channel 3",
    "Current from PDM channel 4",
    "Current from PDM channel 5",
    "Current from PDM channel 6",
    "Current from PDM channel 7",
    "Current from PDM channel 8",
    "Current from PDM channel 9",
    "Current from PDM channel 10",
    "Current from PDM channel 11",
    "Current from PDM channel 12",
    "Current from PDM channel 13",
    "Current from PDM channel 14",
    "Current from PDM channel 15",
    "Current from PDM channel 16",
    "Current from PDM channel 17",
    "Current from PDM channel 18",
    "Current from PDM channel 19",
    "Switch Voltage",
    "Switch Temperature"
    
};

// parameter units
char* unit_strings[NUM_OF_PARAMETERS] =
{
    "cmd",
    "rpm",
    "percent",
    "percent",
    "rpm",
    "km/h",
    "km/h",
    "km/h",
    "km/h",
    "percent",
    "V",
    "C",
    "C",
    "LA",
    "percent",
    "percent",
    "percent",
    "percent",
    "kPa",
    "percent",
    "dbtdc",
    "kPa",
    "C",
    "kPa",
    "percent",
    "psi",
    "percent",
    "percent",
    "percent",
    "percent",
    "percent",
    "percent",
    "V",
    "V",
    "degrees",
    "degrees",
    "psi",
    "°",
    "number",
    "m/s^2",
    "mm",
    "mm",
    "mm",
    "mm",
    "mm",
    "mm",
    "PSI",
    "PSI",
    "PSI",
    "C",
    "C",
    "PSI",
    "PSI",
    "PSI",
    "C",
    "C",
    "psi",
    "psi",
    "psi",
    "psi",
    "Liters/Minute",
    "C",
    "C",
    "C",
    "C",
    "C",
    "lam",
    "lam",
    "C",
    "C",
    "C",
    "C",
    "C",
    "degrees/s",
    "G",
    "degrees/s",
    "G",
    "G",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "C",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "mm",
    "mm",
    "rpm",
    "rpm",
    "gear",
    "gear",
    "bool",
    "bool",
    "bool",
    "bool",
    "bool",
    "duty",
    "duty",
    "duty",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "mA",
    "Volts",
    "C"
    
};

// parameter types
PARAM_TYPE_t param_types[NUM_OF_PARAMETERS] = 
{
	CMD,
    UINT_16,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    FLOAT,
    FLOAT,
    UINT_32,
    UINT_32,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_8,
    UINT_32,
    UINT_32,
    UINT_32,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT
    
};


// End of GopherCAN_names.c

