// GopherCAN_ids.h
//  This header file houses all of the auto-generated IDs for modules, parameters, and CAN
//  command IDs. This file can be completely auto-generated


#ifndef GOPHERCAN_IDS_H
#define GOPHERCAN_IDS_H

// Generated by GopherCANnon

#define GOPHERCAN_HASH 320255973501901


// Module IDs:
typedef enum
{
    ALL_MODULES_ID = 0,
    DLM_ID = 1,
    DAM_ID = 2,
    PDM_ID = 3,
    TCM_ID = 4,
    ACM_ID = 5,
    DISPLAY_ID = 6,
    
} MODULE_ID;

#define NUM_OF_MODULES 7


// Parameter IDs:
typedef enum
{
    CAN_COMMAND_ID = 0,
    RPM_ID = 1,
    FAN_CURRENT_ID = 2,
    U8_TESTER_ID = 3,
    U16_TESTER_ID = 4,
    U32_TESTER_ID = 5,
    U64_TESTER_ID = 6,
    S8_TESTER_ID = 7,
    S16_TESTER_ID = 8,
    S32_TESTER_ID = 9,
    S64_TESTER_ID = 10,
    FLOAT_TESTER_ID = 11,
    
} GCAN_PARAM;

#define NUM_OF_PARAMETERS 12


// TODO custom command IDs


// Error IDs:
#define ID_NOT_FOUND_ID 0,
#define COMMAND_ID_NOT_FOUND_ID 1,
#define PARAM_NOT_ENABLED_ID 2,
#define SIZE_ERROR_ID 3,
#define DATATYPE_NOT_FOUND_ID 4,
#define COMMAND_NOT_ENABLED_ID 5,



#endif // GOPHERCAN_IDS_H

// this is so this file can be included again when this part is needed
#ifdef AUTOGEN_EXTERNS
#ifndef GOPHERCAN_IDS_H_P2
#define GOPHERCAN_IDS_H_P2

// all of the global parameter struct externs so all files including GopherCAN.h
// have access
CAN_COMMAND_STRUCT CAN_COMMAND;
extern U16_CAN_STRUCT rpm,
extern U8_CAN_STRUCT fan_current,
extern U8_CAN_STRUCT u8_tester,
extern U16_CAN_STRUCT u16_tester,
extern U32_CAN_STRUCT u32_tester,
extern U64_CAN_STRUCT u64_tester,
extern S8_CAN_STRUCT s8_tester,
extern S16_CAN_STRUCT s16_tester,
extern S32_CAN_STRUCT s32_tester,
extern S64_CAN_STRUCT s64_tester,
extern FLOAT_CAN_STRUCT float_tester,


#endif // GOPHERCAN_IDS_H_P2
#endif // AUTOGEN_EXTERNS


// End of GopherCAN_ids.h


// start of GopherCAN.c auto-gen

// ******** BEGIN AUTO GENERATED ********

// all of the global parameter structs
CAN_COMMAND_STRUCT CAN_COMMAND;
extern U16_CAN_STRUCT rpm,
extern U8_CAN_STRUCT fan_current,
extern U8_CAN_STRUCT u8_tester,
extern U16_CAN_STRUCT u16_tester,
extern U32_CAN_STRUCT u32_tester,
extern U64_CAN_STRUCT u64_tester,
extern S8_CAN_STRUCT s8_tester,
extern S16_CAN_STRUCT s16_tester,
extern S32_CAN_STRUCT s32_tester,
extern S64_CAN_STRUCT s64_tester,
extern FLOAT_CAN_STRUCT float_tester,


// this is the struct that will be used to reference based on ID
void* all_parameter_structs[NUM_OF_PARAMETERS] =
{
        &can_command,
        &rpm,
        &fan_current,
        &u8_tester,
        &u16_tester,
        &u32_tester,
        &u64_tester,
        &s8_tester,
        &s16_tester,
        &s32_tester,
        &s64_tester,
        &float_tester,
        
};


// TODO parameter_data_types

// TODO multiple busses defines

// ******** END AUTO GENERATED ********

// End of GopherCAN.c auto-gen