// GopherCAN_names.h
//  (auto-generated)
//  This header file houses externs for the param names in GopherCAN


#ifndef GOPHERCAN_NAMES_H
#define GOPHERCAN_NAMES_H

// Generated by GopherCANnon

#ifndef NUM_OF_PARAMETERS
#define NUM_OF_PARAMETERS 50
#endif // NUM_OF_PARAMETERS

extern char* name_strings[NUM_OF_PARAMETERS];
extern char* unit_strings[NUM_OF_PARAMETERS];

#endif // GOPHERCAN_NAMES_H

// End of GopherCAN_names.h

