buses:
    - GCAN0
    - GCAN1
    - GCAN2

modules:
    PLM:
        id: 1
        buses:
            - GCAN0
            - GCAN1
            - GCAN2
    DAM_FR:
        id: 2
        buses:
            - GCAN0
    DAM_RL:
        id: 3
        buses:
            - GCAN1
    DAM_RR:
        id: 4
        buses:
            - GCAN2
    PDM:
        id: 5
        buses:
            - GCAN0
    TCM:
        id: 6
        buses:
            - GCAN1
    ACM:
        id: 7
        buses:
            - GCAN0

parameters:
    u8_tester:
        id: 1
        motec_name: U8 Tester
        unit: number
        type: UNSIGNED8
        encoding: MSB
        scale: 1
        offset: 0

    u16_tester:
        id: 2
        motec_name: U16 Tester
        unit: number
        type: UNSIGNED16
        encoding: MSB
        scale: 1
        offset: 0

    u32_tester:
        id: 3
        motec_name: U32 Tester
        unit: number
        type: UNSIGNED32
        encoding: MSB
        scale: 1
        offset: 0

    u64_tester:
        id: 4
        motec_name: U64 Tester
        unit: number
        type: UNSIGNED64
        encoding: MSB
        scale: 1
        offset: 0

    s8_tester:
        id: 5
        motec_name: S8 Tester
        unit: number
        type: SIGNED8
        encoding: MSB
        scale: 1
        offset: 0

    s16_tester:
        id: 6
        motec_name: S16 Tester
        unit: number
        type: SIGNED16
        encoding: MSB
        scale: 1
        offset: 0

    s32_tester:
        id: 7
        motec_name: S32 Tester
        unit: number
        type: SIGNED32
        encoding: MSB
        scale: 1
        offset: 0

    s64_tester:
        id: 8
        motec_name: S64 Tester
        unit: number
        type: SIGNED64
        encoding: MSB
        scale: 1
        offset: 0

    # 8 bit, [0-25.5]
    float_tester:
        id: 9
        motec_name: Float Tester 1
        unit: number
        type: FLOATING
        encoding: MSB
        scale: 0.1
        offset: 0

    # 16 bit, [0-655.35]
    float_tester_2:
        id: 10
        motec_name: Float Tester 2
        unit: number
        type: FLOATING
        encoding: MSB
        scale: 0.01
        offset: 0

    # 16 bit, [0-65.535]
    float_tester_3:
        id: 11
        motec_name: Float Tester 3
        unit: number
        type: FLOATING
        encoding: MSB
        scale: 0.001
        offset: 0

    # 32 bit, [0-429496.7296] (floats are not this precise)
    float_tester_4:
        id: 12
        motec_name: Float Tester 4
        unit: number
        type: FLOATING
        encoding: MSB
        scale: 0.0001
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_1:
        id: 13
        motec_name: DAM Channel 1
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_2:
        id: 14
        motec_name: DAM Channel 2
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_3:
        id: 15
        motec_name: DAM Channel 3
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_4:
        id: 16
        motec_name: DAM Channel 4
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_5:
        id: 17
        motec_name: DAM Channel 5
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_6:
        id: 18
        motec_name: DAM Channel 6
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_7:
        id: 19
        motec_name: DAM Channel 7
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_8:
        id: 20
        motec_name: DAM Channel 8
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_9:
        id: 21
        motec_name: DAM Channel 9
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    # 0-50 (sending mm from pot onto 16bit number)
    dam_chan_10:
        id: 22
        motec_name: DAM Channel 10
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 0.000762939453125 # [0-50] -> [0-65535]
        offset: 0

    voltageSensor1_V:
        id: 23
        motec_name: Voltage Sensor 1
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor2_V:
        id: 24
        motec_name: Voltage Sensor 2
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor3_V:
        id: 25
        motec_name: Voltage Sensor 3
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor4_V:
        id: 26
        motec_name: Voltage Sensor 4
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor5_V:
        id: 27
        motec_name: Voltage Sensor 5
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor6_V:
        id: 28
        motec_name: Voltage Sensor 6
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor7_V:
        id: 29
        motec_name: Voltage Sensor 7
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor8_V:
        id: 30
        motec_name: Voltage Sensor 8
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor9_V:
        id: 31
        motec_name: Voltage Sensor 9
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor10_V:
        id: 32
        motec_name: Voltage Sensor 10
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor11_V:
        id: 33
        motec_name: Voltage Sensor 11
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    voltageSensor12_V:
        id: 34
        motec_name: Voltage Sensor 12
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    pulseSensor1_V:
        id: 35
        motec_name: Pulse Sensor 1
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    pulseSensor2_V:
        id: 36
        motec_name: Pulse Sensor 2
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    pulseSensor3_V:
        id: 37
        motec_name: Pulse Sensor 3
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

    pulseSensor4_V:
        id: 38
        motec_name: Pulse Sensor 4
        unit: V
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

        # 0-50 (sending mm from pot onto 16bit number)
    lapBeacon_ul:
        id: 39
        motec_name: Lap Beacon Test
        unit: mm
        type: FLOATING
        encoding: MSB
        scale: 1
        offset: 0

groups: [
    {
        id: 0x1,
        parameters: [
            {name: u8_tester, start: 0, length: 1},
            {name: u16_tester, start: 1, length: 2},
            {name: u32_tester, start: 3, length: 4}
        ]
    },
    {
        id: 0x2,
        parameters: [
            {name: u64_tester, start: 0, length: 8}
        ]
    },
    {
        id: 0x3,
        parameters: [
            {name: s8_tester, start: 0, length: 1},
            {name: s16_tester, start: 1, length: 2},
            {name: s32_tester, start: 3, length: 4}
        ]
    },
    {
        id: 0x4,
        parameters: [
            {name: s64_tester, start: 0, length: 8}
        ]
    },
    {
        id: 0x5,
        parameters: [
            {name: float_tester, start: 0, length: 1},
            {name: float_tester_2, start: 1, length: 2},
            {name: float_tester_3, start: 3, length: 2}
        ]
    },
    {
        id: 0x6,
        parameters: [
            {name: float_tester_4, start: 0, length: 4}
        ]
    },
    {
        id: 0x7,
        parameters: [
            {name: dam_chan_1, start: 0, length: 2},
            {name: dam_chan_2, start: 2, length: 2},
            {name: dam_chan_3, start: 4, length: 2},
            {name: dam_chan_4, start: 6, length: 2}
        ]
    },
    {
        id: 0x8,
        parameters: [
            {name: dam_chan_5, start: 0, length: 2},
            {name: dam_chan_6, start: 2, length: 2},
            {name: dam_chan_7, start: 4, length: 2},
            {name: dam_chan_8, start: 6, length: 2}
        ]
    },
    {
        id: 0x9,
        parameters: [
            {name: dam_chan_9, start: 0, length: 2},
            {name: dam_chan_10, start: 2, length: 2},
            {name: lapBeacon_ul, start: 4, length: 2}
        ]
    },
    {
        id: 0xA,
        parameters: [
            {name: voltageSensor1_V, start: 0, length: 2},
            {name: voltageSensor2_V, start: 2, length: 2},
            {name: voltageSensor3_V, start: 4, length: 2},
            {name: voltageSensor4_V, start: 6, length: 2}
        ]
    },
    {
        id: 0xB,
        parameters: [
            {name: voltageSensor5_V, start: 0, length: 2},
            {name: voltageSensor6_V, start: 2, length: 2},
            {name: voltageSensor7_V, start: 4, length: 2},
            {name: voltageSensor8_V, start: 6, length: 2}
        ]
    },
        {
        id: 0xC,
        parameters: [
            {name: voltageSensor9_V, start: 0, length: 2},
            {name: voltageSensor10_V, start: 2, length: 2},
            {name: voltageSensor11_V, start: 4, length: 2},
            {name: voltageSensor12_V, start: 6, length: 2}
        ]
    },
        {
        id: 0xD,
        parameters: [
            {name: pulseSensor1_V, start: 0, length: 2},
            {name: pulseSensor2_V, start: 2, length: 2},
            {name: pulseSensor3_V, start: 4, length: 2},
            {name: pulseSensor4_V, start: 6, length: 2}
        ]
    }
]

commands:
    0: SET_LED_STATE # args: (LED state, _, _, _)
    1: SET_RTC_TIME # args: (hour, min, sec, _)
    2: SET_RTC_DATE # args: (year, month, day, weekday)
    3: LOG_COMPLETE # args: (_, _, _, _)

errors:
    0: ID_NOT_FOUND
    1: COMMAND_ID_NOT_FOUND
    2: PARAM_NOT_ENABLED
    3: SIZE_ERROR
    4: DATATYPE_NOT_FOUND
    5: COMMAND_NOT_ENABLED
